steps:
  # 1) Build Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/member-qa-service:$COMMIT_SHA"
      - "."

  # 2) Push image to Container Registry / Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/member-qa-service:$COMMIT_SHA"

  # 3) Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "member-qa-service"
      - "--image"
      - "gcr.io/$PROJECT_ID/member-qa-service:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "8080"

images:
  - "gcr.io/$PROJECT_ID/member-qa-service:$COMMIT_SHA"
